//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CentersAPI.Models.EFModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class ApplicationVersoin
    {
        public int Id { get; set; }
        public double VersionNumber { get; set; }
        public System.DateTime Date { get; set; }
        public bool IsOptinal { get; set; }
        public string Features { get; set; }
    }
}
