//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CentersAPI.Models.EFModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cours
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Cours()
        {
            this.Applications = new HashSet<Application>();
            this.CourseStudents = new HashSet<CourseStudent>();
            this.CoursLoves = new HashSet<CoursLove>();
        }
    
        public int Id { get; set; }
        public string uid { get; set; }
        public string Name { get; set; }
        public int Hours { get; set; }
        public System.DateTime BeginDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public System.DateTime BeginTime { get; set; }
        public System.DateTime EndTime { get; set; }
        public string Instructor { get; set; }
        public string Description { get; set; }
        public string PreRequest { get; set; }
        public string Audience { get; set; }
        public int AudienceCount { get; set; }
        public decimal Price { get; set; }
        public int CategoryId { get; set; }
        public int CourseTypeId { get; set; }
        public byte[] Logo { get; set; }
        public string Outline { get; set; }
        public int CenterId { get; set; }
        public int branchId { get; set; }
        public bool isForBranch { get; set; }
        public bool isFinished { get; set; }
        public bool isStarted { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Application> Applications { get; set; }
        public virtual Category Category { get; set; }
        public virtual Center Center { get; set; }
        public virtual CourseType CourseType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CourseStudent> CourseStudents { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CoursLove> CoursLoves { get; set; }
    }
}
