//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CentersAPI.Models.EFModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class Log
    {
        public int Id { get; set; }
        public string userId { get; set; }
        public string Action { get; set; }
        public System.DateTime DateTime { get; set; }
        public int Narration { get; set; }
        public bool IsException { get; set; }
        public bool isCurrected { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
    }
}
