//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CentersAPI.Models.EFModels
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<Application> Applications { get; set; }
        public virtual DbSet<ApplicationVersoin> ApplicationVersoins { get; set; }
        public virtual DbSet<AspNetRole> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaim> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogin> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUser> AspNetUsers { get; set; }
        public virtual DbSet<Category> Categories { get; set; }
        public virtual DbSet<CenterBranch> CenterBranches { get; set; }
        public virtual DbSet<CenterBrancheUser> CenterBrancheUsers { get; set; }
        public virtual DbSet<CenterBranchImage> CenterBranchImages { get; set; }
        public virtual DbSet<CenterCertificatePath> CenterCertificatePaths { get; set; }
        public virtual DbSet<CenterFollower> CenterFollowers { get; set; }
        public virtual DbSet<CenterImage> CenterImages { get; set; }
        public virtual DbSet<CenterRate> CenterRates { get; set; }
        public virtual DbSet<Center> Centers { get; set; }
        public virtual DbSet<CenterUser> CenterUsers { get; set; }
        public virtual DbSet<Cours> Courses { get; set; }
        public virtual DbSet<CourseStudent> CourseStudents { get; set; }
        public virtual DbSet<CourseType> CourseTypes { get; set; }
        public virtual DbSet<CoursLove> CoursLoves { get; set; }
        public virtual DbSet<EndUser> EndUsers { get; set; }
        public virtual DbSet<Log> Logs { get; set; }
        public virtual DbSet<Notification> Notifications { get; set; }
        public virtual DbSet<Setting> Settings { get; set; }
        public virtual DbSet<TrainningCenterCategory> TrainningCenterCategories { get; set; }
        public virtual DbSet<UserCategory> UserCategories { get; set; }
        public virtual DbSet<UserFavourite> UserFavourites { get; set; }
    }
}
