//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CentersAPI.Models.EFModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class TrainningCenterCategory
    {
        public int Id { get; set; }
        public int CentersId { get; set; }
        public int CategoryId { get; set; }
        public Nullable<int> CenterId { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual Center Center { get; set; }
    }
}
