//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CentersAPI.Models.EFModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserSearchHistory
    {
        public int Id { get; set; }
        public int UserId { get; set; }
        public string Keyword { get; set; }
        public string Result { get; set; }
    
        public virtual EndUser EndUser { get; set; }
    }
}
